services:
  # Web Service (Node.js API + Frontend)
  - type: web
    name: poker-profiles
    runtime: node
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: poker-profiles-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DEV
        value: "false"

databases:
  # PostgreSQL Database
  - name: poker-profiles-db
    plan: free
    databaseName: pokerprofiles
    user: pokerprofiles
    postgresMajorVersion: 15
